import { notFound } from "next/navigation"
import {
  generateManagementNotificationEmail,
  generateReservationConfirmationEmail,
  generateStatusUpdateEmail,
} from "@/lib/email-service"

type EmailPreview = {
  id: string
  title: string
  subject: string
  html: string
}

const sampleReservation = {
  customerName: "Ayse Yilmaz",
  restaurantName: "Felix Selimiye",
  reservationAreaName: "Marina Terrace",
  reservationDate: "18 May 2026",
  reservationTime: "20:30",
  partySize: 4,
  reservationType: "meal",
}

function buildPreviews(): EmailPreview[] {
  const confirmationEn = generateReservationConfirmationEmail({
    ...sampleReservation,
    lang: "en",
  })
  const confirmationTr = generateReservationConfirmationEmail({
    ...sampleReservation,
    lang: "tr",
  })
  const managementCreated = generateManagementNotificationEmail({
    action: "created",
    ...sampleReservation,
    customerEmail: "ayse@example.com",
    customerPhone: "+90 532 000 00 00",
    specialRequests: "Window-side table if available.",
    reservationId: "rez_sample_001",
  })
  const managementUpdated = generateManagementNotificationEmail({
    action: "updated",
    ...sampleReservation,
    partySize: 6,
    customerEmail: "ayse@example.com",
    customerPhone: "+90 532 000 00 00",
    specialRequests: "Guest count changed from 4 to 6.",
    reservationId: "rez_sample_001",
  })
  const confirmedEn = generateStatusUpdateEmail({
    ...sampleReservation,
    status: "confirmed",
    notes: "Your table is confirmed. We look forward to welcoming you.",
    lang: "en",
  })
  const confirmedTr = generateStatusUpdateEmail({
    ...sampleReservation,
    status: "confirmed",
    notes: "Masaniz onaylandi. Sizi agirlamayi bekliyoruz.",
    lang: "tr",
  })
  const cancelledEn = generateStatusUpdateEmail({
    ...sampleReservation,
    status: "cancelled",
    notes: "We are unable to host this reservation time.",
    lang: "en",
  })
  const cancelledTr = generateStatusUpdateEmail({
    ...sampleReservation,
    status: "cancelled",
    notes: "Bu rezervasyon saati icin uygunluk bulunmuyor.",
    lang: "tr",
  })

  return [
    { id: "confirmation-en", title: "Reservation received - EN", ...confirmationEn },
    { id: "confirmation-tr", title: "Reservation received - TR", ...confirmationTr },
    { id: "management-created", title: "Management notification - Created", ...managementCreated },
    { id: "management-updated", title: "Management notification - Updated", ...managementUpdated },
    { id: "status-confirmed-en", title: "Status confirmed - EN", ...confirmedEn },
    { id: "status-confirmed-tr", title: "Status confirmed - TR", ...confirmedTr },
    { id: "status-cancelled-en", title: "Status cancelled - EN", ...cancelledEn },
    { id: "status-cancelled-tr", title: "Status cancelled - TR", ...cancelledTr },
  ]
}

export default function EmailPreviewPage() {
  if (process.env.NODE_ENV === "production") {
    notFound()
  }

  const previews = buildPreviews()

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-8 text-slate-950">
      <div className="mx-auto max-w-6xl">
        <header className="mb-8">
          <h1 className="text-3xl font-semibold tracking-tight">Email Previews</h1>
          <p className="mt-2 max-w-2xl text-sm text-slate-600">
            Local preview page for reservation email templates generated by lib/email-service.ts.
          </p>
        </header>

        <nav className="mb-8 flex flex-wrap gap-2">
          {previews.map((preview) => (
            <a
              key={preview.id}
              href={`#${preview.id}`}
              className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm hover:border-slate-400"
            >
              {preview.title}
            </a>
          ))}
        </nav>

        <div className="space-y-10">
          {previews.map((preview) => (
            <section id={preview.id} key={preview.id} className="scroll-mt-6">
              <div className="mb-3">
                <h2 className="text-xl font-semibold">{preview.title}</h2>
                <p className="mt-1 text-sm text-slate-600">
                  <span className="font-medium text-slate-700">Subject:</span> {preview.subject}
                </p>
              </div>
              <div className="overflow-hidden rounded-lg border border-slate-300 bg-white shadow-sm">
                <iframe
                  title={preview.title}
                  srcDoc={preview.html}
                  className="h-[760px] w-full bg-white"
                  sandbox=""
                />
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  )
}
